import type {AssistantTriggerRule} from './types';

export const assistantTriggerRules: AssistantTriggerRule[] = [
  {
    id: 'home_first_enter',
    page: 'home',
    trigger: 'page_enter',
    text: '晚上好，我今天也会陪你一起创作。',
    style: 'gentle',
    priority: 100,
    cooldownMs: 60 * 60 * 1000,
    action: 'open_half',
  },
  {
    id: 'home_idle_hint',
    page: 'home',
    trigger: 'idle_timeout',
    text: '我可以先帮你想一个适合今天的风格。',
    style: 'professional',
    priority: 80,
    cooldownMs: 45 * 1000,
    action: 'open_half',
  },
  {
    id: 'capture_enter_hint',
    page: 'capture',
    trigger: 'page_enter',
    text: '拍的时候不用想太多，我会提醒你。',
    style: 'gentle',
    priority: 90,
    cooldownMs: 30 * 1000,
    action: 'none',
  },
  {
    id: 'editor_enter_hint',
    page: 'editor',
    trigger: 'page_enter',
    text: '这张照片我已经看过了，我有几个优化建议。',
    style: 'professional',
    priority: 90,
    cooldownMs: 30 * 1000,
    action: 'open_half',
  },
  {
    id: 'editor_task_done',
    page: 'editor',
    trigger: 'task_completed',
    text: '已经调整好了，你可以看看现在的感觉。',
    style: 'gentle',
    priority: 120,
    cooldownMs: 20 * 1000,
    action: 'none',
  },
  {
    id: 'works_page_hint',
    page: 'works',
    trigger: 'page_enter',
    text: '要不要把这套风格保存下来，下次继续用？',
    style: 'professional',
    priority: 70,
    cooldownMs: 60 * 1000,
    action: 'open_half',
  },
];
